name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4

    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version-file: ".nvmrc"
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
