name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version-file: ".nvmrc"
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
